#!/bin/bash

set -e

ANDROID_COMPILE_SDK="27"
ANDROID_BUILD_TOOLS="27.0.3"

cd /opt

wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
unzip -q android-sdk.zip -d android-sdk-linux
rm android-sdk.zip

mkdir android-sdk-linux/licenses
printf "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
printf "\n84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
android-sdk-linux/tools/bin/sdkmanager --update > update.log
android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log
